### PR TITLE
Move pytest dependency (#883)

### PR DESCRIPTION
**Pull request by astachowiczhabana**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by mandy-li** [comment]
@astachowiczhabana , @regisss , in https://github.com/huggingface/optimum-habana/blob/main/setup.py, we have "huggingface_hub < 0.23.0", as well. Do we need to add it in OH-fork?

**Comment by regisss** [comment]
I need it for CI otherwise some 8x runs fail when downloading some models with v0.23. Other than that it should be fine.

**Comment by mandy-li** [comment]
@astachowiczhabana , you can decide if you need it in our planning CI runs in OH-fork

**Review by mandy-li — APPROVED** [review]

**Comment by astachowiczhabana** [comment]
Unmatched PR

**Pull request merged**
