### PR TITLE
Revert "[SW-185803] Enable FusedSDPA fp8 in Llama FT (#291)"

### PR DESCRIPTION
**Pull request by MrGeva**
This reverts commit 35f6fbe373de8294f4d88d5bd854360ecf99daa2.

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by vivekgoe** [comment]
@MrGeva Can you please share JIRA or some other description about the issue this commit is causing? Will approve revert immediately if there is no quick fix available. Thanks.

**Review by dudilester — APPROVED** [review]
looks good to me

**Review by vivekgoe — CHANGES_REQUESTED** [review]
Please share reason for revert before merging revert.

**Comment by MrGeva** [comment]
> @MrGeva Can you please share JIRA or some other description about the issue this commit is causing? Will approve revert immediately if there is no quick fix available. Thanks. FYI @pbielak @wszczurekhabana

https://jira.habana-labs.com/browse/SW-192667

**Review by wszczurekhabana — APPROVED** [review]

**Comment by wszczurekhabana** [comment]
@MrGeva @vivekgoe let's revert. We are working out the reason of failure on inference code path.

**Pull request merged**
