### PR TITLE
Remove usage of clear cache

### PR DESCRIPTION
**Pull request by puneeshkhanna**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by MrGeva** [comment]
have you tested accuracy impact ?

**Comment by puneeshkhanna** [comment]
@MrGeva  - https://github.com/HabanaAI/optimum-habana-fork/pull/36 - I had pushed an additional change of clear cache as part of bucketing changes. However it seems to have introduced a regression in falcon perf. No relation with accuracy. In this PR, I am just reverting the clear cache change from the bucketing changes. 

We may want to push this as separate PR in future if it saves memory for HPU graphs and with no significant impact on performance.

**Comment by puneeshkhanna** [comment]
ohh wait, modeling llama changes also got pushed. Let me revert.

**Comment by mandy-li** [comment]
@puneeshkhanna , without using clear_cache(), how many additional memory does llama2-70b use?

**Comment by puneeshkhanna** [comment]
@mandy-li  - will come with specific cases in another PR, anyways clear cache has not been there yet till we merged #36 very recently.

**Review by mandy-li — APPROVED** [review]

**Review by dvarshney-habana — APPROVED** [review]

**Pull request merged**
