### PR TITLE
Update ckpt loading

### PR DESCRIPTION
**Pull request by schoi-habana**
PR#15 reads a set of ckpt file names from the index json file.
When OH downloads files from the hub instead of loading from a cache dir, get_repo_root() skips downloading the index json file. Thus the PR#15 fails to load file names.
This PR scans the path and returns a list of names that matches the pattern

Tested the models in cache dir:
Falcon-7b, Falcon-40b, Falcon-180b, Llama-70b

Tested the models downloaded from HF hub:
Falcon-7b, Falcon-40b, TinyLlama

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by mandy-li** [comment]
@schoi-habana , please also test downloaded ckpt for falcon-180b

**Comment by puneeshkhanna** [comment]
@schoi-habana  - WIll this solve llama2 ; right now without your change we see below error:

pickle.UnpicklingError: Memo value not found at index 107
Loading 2 checkpoint shards:   0%|                                                                                                                                                              | 0/2 [00:00<?, ?it/s]
Loading 2 checkpoint shards:   0%|                                                                                                                                                              | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/software/users/pkhanna/optimum-habana-fork/examples/text-generation/run_generation.py", line 626, in <module>
    main()
  File "/software/users/pkhanna/optimum-habana-fork/examples/text-generation/run_generation.py", line 277, in main
    model, tokenizer, generation_config = initialize_model(args, logger)
  File "/software/users/pkhanna/optimum-habana-fork/examples/text-generation/utils.py", line 374, in initialize_model
    else setup_distributed_model(args, model_dtype, model_kwargs, logger)
  File "/software/users/pkhanna/optimum-habana-fork/examples/text-generation/utils.py", line 235, in setup_distributed_model
    model = deepspeed.init_inference(model, **ds_inference_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/__init__.py", line 342, in init_inference
    engine = InferenceEngine(model, config=ds_inference_config)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/inference/engine.py", line 154, in __init__
    self._apply_injection_policy(config, client_module)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/inference/engine.py", line 417, in _apply_injection_policy
    replace_transformer_layer(client_module, self.module, checkpoint, config, self.config)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/module_inject/replace_module.py", line 333, in replace_transformer_layer
    replaced_module = replace_module(model=model,
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/module_inject/replace_module.py", line 571, in replace_module
    sd = torch.load(checkpoint, map_location='cpu')
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1026, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1244, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: Memo value not found at index 107
[2024-02-14 06:40:09,891] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed info: version=0.12.4+f4fa754c, git-hash=f4fa754c, git-branch=HEAD
[2024-02-14 06:40:09,892] [INFO] [logging.py:96:log_dist] [Rank 0] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
Loading 2 checkpoint shards:   0%|                                                                                                                                                              | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/software/users/pkhanna/optimum-habana-fork/examples/text-generation/run_generation.py", line 626, in <module>
    main()
  File "/software/users/pkhanna/optimum-habana-fork/examples/text-generation/run_generation.py", line 277, in main
    model, tokenizer, generation_config = initialize_model(args, logger)
  File "/software/users/pkhanna/optimum-habana-fork/examples/text-generation/utils.py", line 374, in initialize_model
    else setup_distributed_model(args, model_dtype, model_kwargs, logger)
  File "/software/users/pkhanna/optimum-habana-fork/examples/text-generation/utils.py", line 235, in setup_distributed_model
    model = deepspeed.init_inference(model, **ds_inference_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/__init__.py", line 342, in init_inference
    engine = InferenceEngine(model, config=ds_inference_config)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/inference/engine.py", line 154, in __init__
    self._apply_injection_policy(config, client_module)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/inference/engine.py", line 417, in _apply_injection_policy
    replace_transformer_layer(client_module, self.module, checkpoint, config, self.config)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/module_inject/replace_module.py", line 333, in replace_transformer_layer
    replaced_module = replace_module(model=model,
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/module_inject/replace_module.py", line 571, in replace_module
    sd = torch.load(checkpoint, map_location='cpu')
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1026, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1244, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'x'.

**Comment by puneeshkhanna** [comment]
Please tell some 70b command if it works:
python ../gaudi_spawn.py --use_deepspeed --world_size 8 run_generation.py --model_name_or_path /software/
data/llama_inference/Llama-2-70b-hf/ --use_hpu_graphs --use_kv_cache --max_input_tokens 128 --max_new_tokens 1024 --batch_size 16 --attn_softmax_bf16  --trim_logits --bf16 --reuse_cache --warmup 2 --n_iterations 2 --limit_hpu_graphs

**Comment by schoi-habana** [comment]
@puneeshkhanna it may be related to DeepSpeed version, too. I'm aware of that error but couldn't repro in my test env. Which DS version is used in QA?

**Comment by schoi-habana** [comment]
@puneeshkhanna DeepSpeed-fork git-hash=f4fa754c is not latest, there is a change you need to load safetensors. 
Anyway this PR will load bins so no need for you to checkout later changes in DS-fork. Can you test this PR in your env?

**Comment by astachowiczhabana** [comment]
https://github.com/huggingface/optimum-habana/pull/773

**Pull request merged**
