### PR TITLE
Disable SDPA Attention for gpt-bigcode model

### PR DESCRIPTION
**Pull request by jiminha**
# What does this PR do?

Disable SDPA attention until gpt-bigcode model support FusedSDPA attention.

### CODE REVIEW

**Review by vivekgoe — COMMENTED** [review]
@jiminha what issue is this PR fixing?

**Comment by vivekgoe** [comment]
@jiminha It is ok to disable SDPA attention if it is causing problems. But I see a problem with using "_use_sdpa" flag here https://github.com/HabanaAI/optimum-habana-fork/blob/04b07093cdd886448d29740809f16b7933264cd3/optimum/habana/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py#L238 

This creates confusion because "_use_sdpa" is used in transformers to refer to torch SDPA which we should differentiate from habana SDPA.  We already fixed 1 problem related to this for Llama in this PR https://github.com/HabanaAI/optimum-habana-fork/pull/73.

**Review by vivekgoe — APPROVED** [review]
Discussed with @libinta  LGTM

**Comment by vivekgoe** [comment]
Looks good to me. @libinta please go ahead and merge.

**Review by libinta — APPROVED** [review]

**Comment by astachowiczhabana** [comment]
https://github.com/huggingface/optimum-habana/pull/771

**Pull request merged**
