### PR TITLE
fix performance issue in mistral

### PR DESCRIPTION
**Pull request by xin3he**
# What does this PR do?

Fix performance issue in mistral

Without this fix, the first token generation will take more time and the performance is bad.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by hshen14 — APPROVED** [review]

**Comment by MrGeva** [comment]
@libinta @jiminha are you the mistral topology owners? please review this change

**Comment by jiminha** [comment]
@skaulintel Could you test this change and without and check what's the perf gain here?

**Comment by skaulintel** [comment]
@xin3he 

When I run with the following command (no quantization)

` python run_generation.py  --model_name_or_path mistralai/Mistral-7B-Instruct-v0.2 --attn_softmax_bf16 --use_hpu_graphs --trim_logits --use_kv_cache --reuse_cache --bf16 --batch_size 4 --max_new_tokens 512 --max_input_tokens 32000  --use_flash_attention --flash_attention_recompute --limit_hpu_graphs`

I get this error

```
Traceback (most recent call last):
  File "/root/optimum-habana-fork/examples/text-generation/run_generation.py", line 796, in <module>
    main()
  File "/root/optimum-habana-fork/examples/text-generation/run_generation.py", line 566, in main
    generate(None, args.reduce_recompile)
  File "/root/optimum-habana-fork/examples/text-generation/run_generation.py", line 540, in generate
    output_tokens = model.generate(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/optimum-habana-fork/optimum/habana/transformers/generation/utils.py", line 874, in generate
    return self.greedy_search(
  File "/root/optimum-habana-fork/optimum/habana/transformers/generation/utils.py", line 1556, in greedy_search
    torch_hpu.synchronize()
  File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/__init__.py", line 138, in synchronize
    return _hpu_C.synchronize_device()
RuntimeError: Graph compile failed. synStatus=synStatus 26 [Generic failure].
```

**Comment by skaulintel** [comment]
Additionally when testing fp8 with this command I see a regression in performance, 

```
QUANT_CONFIG=./quantization_config/maxabs_quant.json python run_generation.py --model_name_or_path mistralai/Mistral-7B-Instruct-v0.2 --attn_softmax_bf16 --use_hpu_graphs --trim_logits --use_kv_cache --reuse_cache --bf16 --batch_size 120 --max_new_tokens 2048 --max_input_tokens 128 --limit_hpu_graphs
```

before your change
```
Throughput (including tokenization) = 6162.493303960959 tokens/second
Number of HPU graphs                = 85
Memory allocated                    = 74.29 GB
Max memory allocated                = 93.3 GB
Total memory available              = 94.62 GB
Graph compilation duration          = 187.07726455898955 seconds
 ```
 
 after the change
 ```
Throughput (including tokenization) = 3267.6427544593735 tokens/second
Number of HPU graphs                = 28
Memory allocated                    = 24.86 GB
Max memory allocated                = 27.01 GB
Total memory available              = 94.62 GB
Graph compilation duration          = 234.35346834201482 seconds
```

**Review by jiminha — APPROVED** [review]

**Comment by astachowiczhabana** [comment]
https://github.com/huggingface/optimum-habana/pull/1030

**Pull request merged**
