### PR TITLE
add support for TinyLlama model

### PR DESCRIPTION
**Pull request by tjs-intel**
# What does this PR do?

Reopening #19 because #15 does not work for TinyLlama/TinyLlama-1.1B-Chat-v1.0. This model does not have the checkpoint index files.

```
ValueError: Can't find a checkpoint index (pytorch_model.bin.index.json or model.safetensors.index.json) in /root/.cache/huggingface/hub/models--TinyLlama--TinyLlama-1.1B-Chat-v1.0/snapshots/77e23968eed12d195bd46c519aa679cc22a27ddc.
```

The [TinyLlama model](https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0) only has checkpoints in the form of `model.safetensors`. This checkpoint needs to be included in the list of checkpoints that is passed to DeepSpeed in order for the model to function properly when initialized with DeepSpeed.

This PR adds the safetensor checkpoints to the list of checkpoints passed to DeepSpeed.

**Note**: This change requires an [upstream commit in microsoft/DeepSpeed](https://github.com/microsoft/DeepSpeed/commit/c8c57b8c24ad761267ab43b0252fb62f0c30d289) to be merged downstream to HabanaAI/DeepSpeed in order for DeepSpeed to support the provided safetensor format.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by tjs-intel** [comment]
I tested this and it is working with `tiiuae/falcon-7b`, FYI @schoi-habana

**Comment by tjs-intel** [comment]
Tested and working with NousResearch/Nous-Hermes-2-SOLAR-10.7B, upstage/SOLAR-10.7B-Instruct-v1.0, tiiuae/falcon-7b and TinyLlama/TinyLlama-1.1B-Chat-v1.0

**Comment by vivekgoe** [comment]
@schoi-habana @mandy-li  since this is related to https://github.com/HabanaAI/optimum-habana-fork/pull/15 can you please help review this and merge it if it looks ok to you?

**Comment by mandy-li** [comment]
LGTM. @tjs-intel , please rebase your fork repo to get the latest code changes from oh-fork habana-main branch

**Comment by tjs-intel** [comment]
@mandy-li done

**Review by mandy-li — APPROVED** [review]

**Comment by astachowiczhabana** [comment]
https://github.com/huggingface/optimum-habana/pull/831

**Pull request merged**
